---
- name: Install tripwire
  sudo: yes
  apt: name=tripwire

- name: Remove default site key
  sudo: yes
  file: path=/etc/tripwire/site.key state=absent

- name: Generate site key
  sudo: yes
  command: twadmin --generate-keys -S /etc/tripwire/site.key -Q "{{ tripwire_site_passwd }}"

- name: Remove default local key
  sudo: yes
  file: path=/etc/tripwire/{{ ansible_hostname }}-local.key state=absent

- name: Generate local key
  sudo: yes
  command: twadmin --generate-keys -L /etc/tripwire/{{ ansible_hostname }}-local.key -P "{{ tripwire_local_passwd }}"

- name: Install config file
  sudo: yes
  copy: src=twcfg.txt dest=/etc/tripwire

- name: Create config file
  sudo: yes
  command: twadmin --create-cfgfile -S /etc/tripwire/site.key -Q "{{ tripwire_site_passwd }}" /etc/tripwire/twcfg.txt

- name: Remove plaintext config
  sudo: yes
  file: path=/etc/tripwire/twcfg.txt state=absent

- name: Install policy file
  sudo: yes
  copy: src=twpol.txt dest=/etc/tripwire

- name: Create policy file
  sudo: yes
  command: twadmin --create-polfile -S /etc/tripwire/site.key -Q "{{ tripwire_site_passwd }}" /etc/tripwire/twpol.txt

- name: Remove plaintext policy
  sudo: yes
  file: path=/etc/tripwire/twpol.txt state=absent

- name: Initialize db
  sudo: yes
  command: tripwire --init -P "{{ tripwire_local_passwd }}"
